config/routes.rb
Gigbooker::Application.routes.draw do

  root :to => 'static_pages#home' 

  devise_for :users

  resources :bands
  resources :venues do 
    resource :address
  end

end

app/models/address.rb
class Address < ActiveRecord::Base
  belongs_to :venue


end

app/models/band.rb
class Band < ActiveRecord::Base
  has_one :user
  
  validates_presence_of :name, :travel_radius, :location

end

app/models/gig.rb
class Gig < ActiveRecord::Base
  has_and_belongs_to_many :bands
  belongs_to :venue

end

app/models/tag.rb
# class Tag < ActiveRecord::Base
#   has_many :taggings
#   has_many :bands, through: :taggings
#   attr_accessible :name
# end

app/models/tagging.rb
# class Tagging < ActiveRecord::Base
#   belongs_to :band
  
# end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
end

app/models/venue.rb
class Venue < ActiveRecord::Base
  has_one :address
  has_one :user
  has_many :gigs
  has_many :bands, through: :gigs

  accepts_nested_attributes_for :address

  validates_presence_of :name

  

end

app/controllers/addresses_controller.rb
class AddressesController < ApplicationController

  def new
    @address = Address.new
  end

  def create
    @address = Address.new(address_params)
  end

  private

  def address_params
    params.require(:address).permit(:city, :latitude, :longitude, 
                  :postal_code, :state, :street_address, :venue_id, 
                  :venue_attributes)
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
end

app/controllers/bands_controller.rb
class BandsController < ApplicationController
  before_filter :authenticate_user!, except: [:show, :index]
  def new
    @band = Band.new
  end

  def create
    @band = Band.new(band_params)
    if @band.save
      flash[:success] = "Congratulations! Your band has been added!"
      redirect_to @band
    else
      flash[:error] = "Please fill out all fields."
      render 'new'
    end
  end

  def show
    @band = Band.find(params[:id])
  end

  private

  def band_params
    params.require(:band).permit(:name, :travel_radius, :location)
  end
end

app/controllers/static_pages_controller.rb
class StaticPagesController < ApplicationController

  def home
    
  end
end

app/controllers/venues_controller.rb
class VenuesController < ApplicationController
  before_filter :authenticate_user!, except: [:show, :index]

  def new
    @venue = Venue.new
    @address = @venue.build_address(params[:address])
  end

  def create
    @venue = Venue.new(venue_params)
    if @venue.save
      flash[:success] = "Congratulations! Your venue has been added!"
      redirect_to @venue
    else
      flash[:error] = "Please fill out all fields."
      render 'new'
    end
  end

  def show
    @venue = Venue.find(params[:id])
  end

  private

  def venue_params
    params.require(:venue).permit(:name, :address_id, gigs_attributes: [:id, :_destroy, :name],
          address_attributes: [:city, :latitude, :longitude, :postal_code, :state, 
            :street_address]
          )
  end
end

app/helpers/addresses_helper.rb
module AddressesHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/bands_helper.rb
module BandsHelper
  def gravatar_for(band)
    gravatar_id = Digest::MD5::hexdigest(band.contact_email.downcase)
    gravatar_url = "https://secure.gravatar.com/avatar/#{gravatar_id}"
    image_tag(gravatar_url, :size => 80, alt: band.name, class: "gravatar")
  end
end

app/helpers/static_pages_helper.rb
module StaticPagesHelper
end

app/helpers/venues_helper.rb
module VenuesHelper
end

app/views/bands/new.html.haml
.text-center
  %h1 Band Registration Page
  %br
  .form.inline
    = form_for @band do |f|
      = flash[:error]
      = f.label :name, "What is your band's name?"
      = f.text_field :name
      %br
      = f.label :location, "Where is your band located?"
      = f.text_field :location
      %br
      = f.label :travel_radius, "How far are you willing to travel?"
      = f.text_field :travel_radius

      .actions
        = f.submit 'Register my Band!', :class => "btn btn-large btn-primary"

app/views/bands/show.html.haml
= flash[:success]
%br
.row
  .col-lg-3
    #gravatar
      / = gravatar_for @band 

  .col-lg-9
    .info-box
      %h1
        = @band.name
      %br
      %small
        = @band.contact_email
      |
      %small
        = @band.location

app/views/layouts/_navbar.html.haml
.header
  .navbar.navbar-default.navbar-fixed-top
    .container
      .navbar-header
        = link_to "GigBooker", root_path, id: "logo"
      .navbar-collapse.collapse
        %ul.nav.navbar-nav.navbar-right
          %li= link_to "Bands", bands_path
          %li= link_to "Venues", venues_path
          %li= link_to "FAQ"
          %li= link_to "About"
          %li= render 'layouts/user_widget'

app/views/layouts/_user_widget.html.haml
- if user_signed_in? 
  %p  
    = current_user.email
    = link_to 'Logged In [click to logout]', destroy_user_session_path, :method => :delete
- else 
  = link_to 'Login', new_user_session_path 

app/views/layouts/application.html.haml
!!! 5
%html
  %head
    %meta{:name => "viewport", :content => "width=device-width, initial-scale=1"}
    %title Gigbooker
    = stylesheet_link_tag    "application", :media => "all"
    = javascript_include_tag "application"
    = csrf_meta_tags
  = render 'layouts/navbar'
  %body
    .container
      .notice 
        = notice 
      .alert
        = alert
      = yield

      

app/views/static_pages/home.html.haml
.container-narrow
  .jumbotron
    .text-center
      %h1 GigBooker
      %h3 Helping up-and-coming bands find venues.

      %br

      = link_to("Register Your Band!", new_band_path, class: "btn btn-large btn-primary")

      = link_to("Register Your Venue!", new_venue_path, class: "btn btn-large btn-primary")

app/views/venues/new.html.haml
.text-center
  %h1 Venue Registration Page
  %br
  .form.inline
    = form_for @venue do |f|
      = flash[:error]
      = f.label :name, "What is your venue's name?"
      = f.text_field :name
      %br
      = f.label "What is your venue's address?"
      %br
      = f.fields_for :address do |a|
        = a.label :street_address, "Street Address:"
        = a.text_field :street_address
        %br
        = a.label :city, "City:"
        = a.text_field :city
        %br
        = a.label :state, "State:"
        = a.text_field :state
        %br
        = a.label :postal_code, "Postal Code:"
        = a.text_field :postal_code
        %br

      .actions
        = f.submit 'Register my Venue!', :class => "btn btn-large btn-primary"

app/views/venues/show.html.haml
= flash[:success]
%row
  %br
  .info-box
    %h1
      = @venue.name |
      
    %h3
      = @venue.address.street_address
      = @venue.address.city
      = @venue.address.state
      = @venue.address.postal_code